version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: ulake-Hnamenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=ulake-hadoop
    env_file:
      - ./hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: ulake-Hdatanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "ulake-Hnamenode:9870"
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: ulake-Hresourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "ulake-Hnamenode:9000 ulake-Hnamenode:9870 ulake-Hdatanode:9864"
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: ulake-Hnodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "ulake-Hnamenode:9000 ulake-Hnamenode:9870 ulake-Hdatanode:9864 ulake-Hresourcemanager:8088"
    env_file:
      - ./hadoop.env

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: ulake-Hhistoryserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "ulake-Hnamenode:9000 ulake-Hnamenode:9870 ulake-Hdatanode:9864 ulake-Hresourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
