version: '3'

services:
  ulake-Hnamenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    networks:
      - ulake-network
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=ulake-hadoop
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == akswnc4.aksw.uni-leipzig.de

  ulake-Hdatanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    networks:
      - ulake-network
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "ulake-Hnamenode:9870"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

volumes:
  datanode:
  namenode:
  hadoop_historyserver:

networks:
  ulake-network:
    external:
      name: ulake-network
