version: '3'

services:
  ulake-Hdatanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    volumes:
      - /home/hieplnc/Desktop/ulake/deployment/data/hdfs:/hadoop/dfs/data
    networks:
      - ulake-network
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "ulake-Hnamenode:9870"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

networks:
  ulake-network:
    external:
      name: ulake-network
